# Generated by Django 3.1 on 2022-12-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tanlov', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rasm', models.CharField(max_length=255)),
            ],
        ),
    ]
